### ISSUE TITLE
How to load poses?

### ISSUE THREAD

**Issue by edhyah** [AdaRoseCannon/handy-work#13]
Hello!

Newb question. Calling `loadPose` results in me getting a `TypeError: Failed to construct 'URL': Invalid URL` error. I've tried passing in absolute paths, relative paths and so forth - none of them seem to be working. I use webpack and have confirmed that the pose files have been copied over to the bundle.

What am I doing wrong? Thanks!

**Comment by AdaRoseCannon** [comment]
I’ve never actually tried it in a bundle before it is designed to work with es6 modules, and to load the model files themselves as normal files

**Comment by edhyah** [comment]
Ah I got it to work! Essentially just had to load them via a URL, ie. `loadPose('relax', 'http://localhost:3000/' + relaxHandPose)`. Thanks for the quick response!

**Comment by AdaRoseCannon** [comment]
Precisely!
