### ISSUE TITLE
using magnetic helpers as a standalone module to grab objects with hand-tracking-controls

### ISSUE THREAD

**Issue by addy1997** [AdaRoseCannon/handy-work#19]
Hi @AdaRoseCannon,

I was wondering if the magnetic helper module from the handy-work component can be used as a standalone module to grab objects in the scene by pinching.

**Comment by AdaRoseCannon** [comment]
It’s pretty tightly tied to the hand rendering it couldn’t really be separated out. You are welcome to take the magnet logic and try it yourself though.
